"""add source_type to law_cache

Revision ID: 9468f6b0bbc4
Revises: 1d047f36e529
Create Date: 2026-08-04 19:38:18.640274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9468f6b0bbc4'
down_revision: Union[str, Sequence[str], None] = '1d047f36e529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('law_cache', sa.Column('source_type', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('law_cache', 'source_type')
    # ### end Alembic commands ###
